SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN (
        SELECT II.ITEM_ID
        FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT
        WHERE II.ITEM_ID = IT.PARENT_ITEM_ID
        )
ORDER BY ITEM_ID DESC
