SELECT 
    YEAR(STR_TO_DATE(YM, '%Y-%m-%d')) AS YEAR, 
    ROUND(AVG(PM_VAL1), 2) AS PM10, 
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원' AND LOCATION1 = '경기도'
GROUP BY YEAR(STR_TO_DATE(YM, '%Y-%m-%d'))
ORDER BY YEAR(STR_TO_DATE(YM, '%Y-%m-%d')) ASC;
