-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * TOTAL_SALES AS SALES
FROM PRODUCT
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS SALES_SUMMARY
ON PRODUCT.PRODUCT_ID = SALES_SUMMARY.PRODUCT_ID
ORDER BY PRICE * TOTAL_SALES DESC, PRODUCT.PRODUCT_CODE ASC;
