SELECT ID,
    CASE 
        WHEN SIZE <= (SELECT COUNT(*) * 0.25 FROM ECOLI_DATA) THEN 'CRITICAL'
        WHEN SIZE <= (SELECT COUNT(*) * 0.50 FROM ECOLI_DATA) THEN 'HIGH'
        WHEN SIZE <= (SELECT COUNT(*) * 0.75 FROM ECOLI_DATA) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
    FROM ECOLI_DATA
    ) AS ECOLI_SIZE
ORDER BY ID;