SELECT COUNT(FI.FISH_TYPE) as FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO as FI 
JOIN FISH_NAME_INFO as FNI 
    ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FI.FISH_TYPE, FNI.FISH_NAME
ORDER BY FISH_COUNT DESC