SELECT TIME_FORMAT(DATETIME, '%k') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME_FORMAT(DATETIME, '%k') >= 9 AND TIME_FORMAT(DATETIME, '%k') < 20
GROUP BY HOUR
ORDER BY 
    CASE 
        WHEN HOUR >= 10 THEN HOUR END ASC
